# permissions for end users to view ukvs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ukv-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ukv-operator
    app.kubernetes.io/part-of: ukv-operator
    app.kubernetes.io/managed-by: kustomize
  name: ukv-viewer-role
rules:
- apiGroups:
  - unistore.unum.cloud
  resources:
  - ukvs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - unistore.unum.cloud
  resources:
  - ukvs/status
  verbs:
  - get
