# permissions for end users to view ustores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ustore-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ustore-operator
    app.kubernetes.io/part-of: ustore-operator
    app.kubernetes.io/managed-by: kustomize
  name: ustore-viewer-role
rules:
- apiGroups:
  - unum.cloud
  resources:
  - ustores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - unum.cloud
  resources:
  - ustores/status
  verbs:
  - get
