name: Build Main

on:
  push:
    branches: [ main ]

jobs:
  build-main:
    name: Build and push main snapshot images
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v3
     - name: build image
       run: make docker-build
     - name: push image
       run: make docker-push